#!/bin/bash

res=$(echo "logout|reboot|shutdown" | rofi -sep "|" -dmenu -i -p 'Power Menu: ' "" -bw 0 -bc "#212121" -bg "#212121" -fg "#F57C00" -hlbg "#535353" -hlfg "#F57C00" -width 15 -hide-scrollbar -eh 4  -padding 35 -opacity 100 -font "SFNS Regular 10" -auto-select)

if [ $res = "logout" ]; then
    i3-msg exit
fi
if [ $res = "reboot" ]; then
    systemctl reboot
fi
if [ $res = "shutdown" ]; then
    systemctl poweroff
fi
exit 0
